module.exports = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Intro',
    },
    {
      type: 'doc',
      id: 'about',
      label: 'About',
    },
    {
      type: 'category',
      label: 'Information design',
      link: {
        type: 'generated-index',
        title: 'Information design',
        description: 'Navigation and taxonomy examples.',
      },
      items: ['Information design/Navigation', 'Information design/Taxonomi'],
    },
    {
      type: 'category',
      label: 'Docs-as-code',
      link: {
        type: 'generated-index',
        title: 'Docs-as-code',
        description: 'Docs-as-code examples and related documentation.',
      },
      items: [{ type: 'autogenerated', dirName: 'Docs-as-code' }],
    },
    {
      type: 'category',
      label: 'Documentation samples',
      link: {
        type: 'generated-index',
        title: 'Documentation samples',
        description: 'Sample installation and user guides.',
      },
      items: ['Documentation samples/installationguide', 'Documentation samples/userguide'],
    },
  ],
};
